services:
  velxio:
    image: ghcr.io/davidmonterocrespo24/velxio:master
    ports:
      - 3080:80
    volumes:
      - velxio-data:/app/data
      - velxio-arduino-libs:/root/.arduino15
      - velxio-installed-libs:/root/Arduino
      - velxio-ccache:/var/cache/ccache
      - velxio-build:/var/lib/velxio-build
    networks:
      - iot_net

  emqx:
    image: emqx/emqx-enterprise:latest
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    networks:
      iot_net:
        ipv4_address: 172.30.0.10

  tcp_echo:
    build:
      context: ./tcp_echo
      dockerfile: Dockerfile
    container_name: tcp_echo
    ports:
      - 12345:12345
    networks:
      iot_net:
        ipv4_address: 172.30.0.20

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
    networks:
      iot_net:
        ipv4_address: 172.30.0.30

  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      iot_net:
        ipv4_address: 172.30.0.40

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      iot_net:
        ipv4_address: 172.30.0.50

volumes:
  velxio-data:
  velxio-arduino-libs:
  velxio-installed-libs:
  velxio-ccache:
  velxio-build:
  node-red-data:
  influxdb-data:
  grafana-data:

networks:
  iot_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
